// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoOcjSjTRIYs6Prahm0PR4tcb-lwGrzKo',
    appId: '1:346654546620:web:4d2a251091883f521c4eb9',
    messagingSenderId: '346654546620',
    projectId: 'guruh5',
    authDomain: 'guruh5.firebaseapp.com',
    storageBucket: 'guruh5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS52r1ZC824hCXBTgx6OXMsvdriyACWUA',
    appId: '1:346654546620:android:d3ee13570896aa8d1c4eb9',
    messagingSenderId: '346654546620',
    projectId: 'guruh5',
    storageBucket: 'guruh5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6do42kAdtqx85jlgxiVVL85Eo78hEg4',
    appId: '1:346654546620:ios:da37c7f6be0a97cb1c4eb9',
    messagingSenderId: '346654546620',
    projectId: 'guruh5',
    storageBucket: 'guruh5.firebasestorage.app',
    iosBundleId: 'com.example.guruh3',
  );
}
